name: CI

on:
  push:
    branches:
      - '!master'
  workflow_dispatch:
  workflow_call:

jobs:
  # Builds Theta on different Linux versions
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04, ubuntu-18.04 ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} with JDK ${{ matrix.java }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon

  # Tests Theta on different Linux versions
  test-linux:
    needs: [ build-linux ]
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04, ubuntu-18.04 ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }} with JDK ${{ matrix.java }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test --no-daemon

  # Builds Theta on different Windows versions
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, windows-2022, windows-2019 ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} with JDK ${{ matrix.java }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Install VC-Redist 2010 and 2012
        run: |
          Install-Module -Name VcRedist -Force
          $VcList = Get-VcList -Export All | Where-Object { $_.Release -eq "2010" -or $_.Release -eq "2012" }
          Save-VcRedist -VcList $VcList
          Install-VcRedist -VcList $VcList -Silent
      - name: Build with Gradle
        run: .\gradlew.bat build -x test --no-daemon

  # Tests Theta on different Windows versions
  test-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, windows-2022, windows-2019 ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} with JDK ${{ matrix.java }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Install VC-Redist 2010 and 2012
        run: |
          Install-Module -Name VcRedist -Force
          $VcList = Get-VcList -Export All | Where-Object { $_.Release -eq "2010" -or $_.Release -eq "2012" }
          Save-VcRedist -VcList $VcList
          Install-VcRedist -VcList $VcList -Silent
      - name: Test with Gradle
        run: .\gradlew.bat test --no-daemon