name: Publish release to Maven Central
on:
  workflow_dispatch:
jobs:
  gradle:
    name: Run Gradle
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Publish to Maven Staging
        uses: gradle/gradle-build-action@v2
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          PGP_KEY: ${{ secrets.PGP_KEY }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_PWD: ${{ secrets.PGP_PWD }} 
        with:
          arguments: publish
      - name: Close staging and publish release
        uses: gradle/gradle-build-action@v2
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        with:
          arguments: closeAndReleaseRepository
         
